services:
  - type: web
    name: cpa-monitor
    env: python
    plan: free
    pythonVersion: 3.11.10
    buildCommand: pip install -r requirements.txt
    startCommand: python monitor.py
    envVars:
      - key: RINGBA_API_TOKEN
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: RINGBA_ACCOUNT_ID
        sync: false