services:
  - type: web
    name: ringba-webhook
    env: python
    plan: free
    pythonVersion: 3.11.10
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RINGBA_CAMPAIGNS
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: MASTER_CPA_DATA
        sync: false
